; Supervertaler for memoQ - installer
;
; Built with Inno Setup, which is what both memoQ's own PDF Preview tool and the
; Lara plugin use - checked on this machine, where each left the tell-tale
; unins000.exe in its install folder. Following the established pattern rather
; than inventing one means an IT department recognises what it is looking at.
;
; What it places, and why each lands where it does:
;
;   The two plugin assemblies and the prompt editor go into memoQ's Addins
;   folder, because that is the only place memoQ looks. The editor is not an
;   add-in and memoQ never loads it, but the options dialog looks for it beside
;   the plugin, so that is where it lives.
;
;   The preview tool goes into our OWN folder under Program Files, NOT the data
;   folder the development build uses. The data folder is per user and resolves
;   through %APPDATA%, and an elevated install may be running as a different
;   user than the translator - so a per-user path decided during an admin
;   install is a path pointing at the wrong profile. The tool registers itself
;   with memoQ by absolute path at first run, so it is free to live anywhere
;   machine-wide.

#define AppName        "Supervertaler for memoQ"
#define AppPublisher   "Michael Beijer"
#define AppUrl         "https://supervertaler.com"
#define SrcRoot        "..\src"

; Passed in by build-installer.sh, which reads it from the built assembly so the
; installer and the plugin can never disagree about which version this is.
#ifndef AppVersion
  #define AppVersion "0.0.0"
#endif

[Setup]
AppId={{8F3A1C62-5D74-4E28-9B3F-0C7A2E6D5148}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppUrl}
AppSupportURL={#AppUrl}
DefaultDirName={autopf}\Supervertaler for memoQ
DisableDirPage=yes
DisableProgramGroupPage=yes
UninstallDisplayName={#AppName}
UninstallDisplayIcon={app}\Supervertaler.MemoQ.Preview.exe
OutputDir=..\dist
OutputBaseFilename=Supervertaler-for-memoQ-{#AppVersion}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern

; The product's own mark instead of Inno's generic box and disc, which is the
; first thing a customer sees and says nothing about whose software this is.
; Generated by tools/make-wizard-images.ps1 from sv-icon-memoq.svg rather than
; committed, so there is one source of truth for the mark - and it is the
; VERMILLION memoQ colourway, not the blue one Trados wears. The first build
; drew from the blue mark and shipped a memoQ installer in Trados's colour.
WizardImageFile=wizard-large.bmp
WizardSmallImageFile=wizard-small.bmp

; The wizard images go on the PAGES. The title bar, the task bar and the .exe in
; Explorer take their icon from here, and with no SetupIconFile they get Inno's
; generic one - so the pages were branded and the window was not, which is the
; first thing anyone sees and the thing they see again every time they look at
; the file they downloaded. Generated alongside the wizard images, from the same
; mark, at every size Windows asks for.
SetupIconFile=sv-icon-memoq.ico

; The add-in goes under Program Files, so this cannot be a per-user install.
PrivilegesRequired=admin

; memoQ 12 is .NET Framework 4.8 x64, and the add-in loads into memoQ's own
; process, so a 32-bit install would produce an add-in memoQ silently ignores.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
; The stock pages say nothing useful here. The Ready page has nothing to show
; because there is nothing to choose, and the Finish page offers to launch a
; shortcut - when what actually has to happen next is switching the plugin on
; INSIDE memoQ. Installing alone does nothing visible, which is the classic way
; a new user concludes a plugin is broken.
ReadyLabel2a=Supervertaler will be installed into the add-ins folder of every memoQ on this computer, from memoQ 11 up.%n%nmemoQ must be closed. After installing you will need to switch Supervertaler on inside memoQ, which takes a minute and is explained at the end.
FinishedLabel=Supervertaler is installed, but memoQ does not use it yet.%n%nStart memoQ, then:%n%n    1.  Options, Terminology plugins: tick "Perform terminology plugin lookups while working in the translation grid", find Supervertaler terms and tick Enable plugin.%n%n    2.  Options, Default resources, MT settings: tick Supervertaler and say Yes to all languages. Every new project then uses it. For a project you already have open, choose it under Project home, Settings, MT settings instead.%n%nThen restart memoQ once. The full instructions are at docs.supervertaler.com/memoq.

[Files]
; Into the Addins folder of EVERY memoQ from 11 up that is on the computer, not
; only the newest: translators keep an older memoQ for clients who still use it,
; and memoQ 11 is fully supported (2026-09-29). Each memoQ found is a numbered
; slot; a slot with no memoQ behind it installs nothing (Check: HasSlot). Inno
; stores each source file once however many slots use it, and the uninstaller
; removes exactly what each slot put down.
#ifndef SqliteDir
  #error SqliteDir is not defined - build with tools/build-installer.sh
#endif
#define Slots 6
#define Slot 0
#sub SlotFiles
Source: "{#SrcRoot}\Supervertaler.MemoQ\bin\Release\Supervertaler.MemoQ.dll";               DestDir: "{code:SlotAddins|{#Slot}}"; Check: HasSlot({#Slot}); Flags: ignoreversion
Source: "{#SrcRoot}\Supervertaler.MemoQ.Terms\bin\Release\Supervertaler.MemoQ.Terms.dll";   DestDir: "{code:SlotAddins|{#Slot}}"; Check: HasSlot({#Slot}); Flags: ignoreversion
Source: "{#SrcRoot}\Supervertaler.PromptEditor\bin\Release\Supervertaler.PromptEditor.exe"; DestDir: "{code:SlotAddins|{#Slot}}"; Check: HasSlot({#Slot}); Flags: ignoreversion
Source: "..\dist\Supervertaler-for-memoQ-MCP-Server.mcpb";                                 DestDir: "{code:SlotAddins|{#Slot}}"; Check: HasSlot({#Slot}); Flags: ignoreversion
Source: "{#SqliteDir}\Microsoft.Data.Sqlite.dll";               DestDir: "{code:SlotAddins|{#Slot}}"; Check: SlotNeedsSqlite({#Slot}); Flags: ignoreversion
Source: "{#SqliteDir}\SQLitePCLRaw.core.dll";                   DestDir: "{code:SlotAddins|{#Slot}}"; Check: SlotNeedsSqlite({#Slot}); Flags: ignoreversion
Source: "{#SqliteDir}\SQLitePCLRaw.batteries_v2.dll";           DestDir: "{code:SlotAddins|{#Slot}}"; Check: SlotNeedsSqlite({#Slot}); Flags: ignoreversion
Source: "{#SqliteDir}\SQLitePCLRaw.provider.dynamic_cdecl.dll"; DestDir: "{code:SlotAddins|{#Slot}}"; Check: SlotNeedsSqlite({#Slot}); Flags: ignoreversion
Source: "{#SqliteDir}\e_sqlite3.dll"; DestDir: "{code:SlotAddins|{#Slot}}\runtimes\win-x64\native"; Check: SlotNeedsSqlite({#Slot}); Flags: ignoreversion
#endsub
#for {Slot = 0; Slot < Slots; Slot++} SlotFiles

; What each slot carries, and why:
;
; - The add-in, the terminology add-in and the editor.
; - The Claude Desktop extension, beside the editor because that is where the
;   editor looks for it - the Connect AI assistant dialog opens it for the user
;   rather than sending them to a download page. memoQ ignores it: it scans this
;   folder for assemblies carrying a Module attribute, and this is a zip. It is
;   an order of magnitude larger than everything else put together, accepted on
;   purpose: an installer that carries it works with no network.
; - SQLite, ONLY for a memoQ that does not ship Microsoft.Data.Sqlite itself
;   (memoQ 11; memoQ 12 has its own and is never given a second copy). Supervertaler's
;   termbases need it. The four managed files sit in Addins, where memoQ's probing
;   finds them. The native e_sqlite3.dll must NOT: memoQ loads every .dll in Addins
;   as an assembly at start-up, and a native one fails with BadImageFormatException.
;   SQLitePCLRaw looks for it under runtimes\win-x64\native beside itself, which
;   memoQ's scan does not enter. Pinned by SHA-256 in build-installer.sh.

; The live document link, in our own folder.
Source: "{#SrcRoot}\Supervertaler.MemoQ.Preview\bin\Release\Supervertaler.MemoQ.Preview.exe";        DestDir: "{app}"; Flags: ignoreversion
Source: "{#SrcRoot}\Supervertaler.MemoQ.Preview\bin\Release\Supervertaler.MemoQ.Preview.exe.config"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Michael pinned the editor to his Start Menu by hand and wanted customers to
; get that without doing it themselves. The tile takes its icon from the exe's
; own Win32 icon, which already carries the mark, so nothing else is needed.
Name: "{autoprograms}\Supervertaler for memoQ"; Filename: "{code:MemoQAddins}\Supervertaler.PromptEditor.exe"

[Code]
const
  { memoQ 11 is the oldest version tested (2026-09-29). Older ones are left
    alone until someone has tried them: installing into a memoQ that cannot
    load the add-in only buys an error at every start. }
  OldestMemoQ = 11;
  MaxSlots = 6;

var
  { Every memoQ found, newest first. MemoQDir is the newest, for the Start Menu
    shortcut, which there is one of. }
  MemoQDirs: array of String;
  MemoQDir: String;

procedure FindAllMemoQ();
var
  Base, Name: String;
  Rec: TFindRec;
  Nums: array of Integer;
  Num, I, J, T: Integer;
  S: String;
begin
  SetArrayLength(MemoQDirs, 0);
  SetArrayLength(Nums, 0);
  Base := ExpandConstant('{commonpf}') + '\memoQ';
  if not DirExists(Base) then Exit;

  if FindFirst(Base + '\memoQ-*', Rec) then
  begin
    try
      repeat
        Name := Rec.Name;
        if (Rec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
        begin
          { "memoQ-12" -> 12. A folder whose name carries no number comes
            back as -1 and is skipped rather than guessed at. }
          Num := StrToIntDef(Copy(Name, 7, Length(Name)), -1);
          if (Num >= OldestMemoQ) and FileExists(Base + '\' + Name + '\memoQ.exe') then
          begin
            SetArrayLength(MemoQDirs, GetArrayLength(MemoQDirs) + 1);
            SetArrayLength(Nums, GetArrayLength(Nums) + 1);
            MemoQDirs[GetArrayLength(MemoQDirs) - 1] := Base + '\' + Name;
            Nums[GetArrayLength(Nums) - 1] := Num;
          end;
        end;
      until not FindNext(Rec);
    finally
      FindClose(Rec);
    end;
  end;

  { Newest first. A handful of entries, so a plain exchange sort. }
  for I := 0 to GetArrayLength(Nums) - 2 do
    for J := I + 1 to GetArrayLength(Nums) - 1 do
      if Nums[J] > Nums[I] then
      begin
        T := Nums[I]; Nums[I] := Nums[J]; Nums[J] := T;
        S := MemoQDirs[I]; MemoQDirs[I] := MemoQDirs[J]; MemoQDirs[J] := S;
      end;

  { More memoQs than slots: the newest ones get Supervertaler. }
  if GetArrayLength(MemoQDirs) > MaxSlots then SetArrayLength(MemoQDirs, MaxSlots);

  if GetArrayLength(MemoQDirs) > 0 then MemoQDir := MemoQDirs[0] else MemoQDir := '';
end;

function HasSlot(Slot: Integer): Boolean;
begin
  Result := Slot < GetArrayLength(MemoQDirs);
end;

function SlotAddins(Param: String): String;
begin
  Result := MemoQDirs[StrToInt(Param)] + '\Addins';
end;

{ Only a memoQ that does not ship Microsoft.Data.Sqlite gets our copy; one that
  has it (memoQ 12) keeps using its own and is never given a second. }
function SlotNeedsSqlite(Slot: Integer): Boolean;
begin
  Result := HasSlot(Slot) and not FileExists(MemoQDirs[Slot] + '\Microsoft.Data.Sqlite.dll');
end;

function MemoQAddins(Param: String): String;
begin
  Result := MemoQDir + '\Addins';
end;

{ memoQ holds the add-in open, so copying over it fails with a sharing violation
  that names nothing useful. Said plainly instead, and before anything is
  written - and the same applies to REMOVING the files, which is why the
  uninstaller asks too. An uninstall that half-succeeds leaves memoQ loading a
  plugin the user believes they removed. }
function MemoQIsRunning(): Boolean;
var
  Res: Integer;
begin
  Result := False;
  if Exec(ExpandConstant('{cmd}'), '/C tasklist /FI "IMAGENAME eq memoQ.exe" | find /I "memoQ.exe"',
          '', SW_HIDE, ewWaitUntilTerminated, Res) then
    Result := (Res = 0);
end;

function InitializeSetup(): Boolean;
begin
  Result := False;

  FindAllMemoQ();
  if MemoQDir = '' then
  begin
    MsgBox('memoQ 11 or later was not found on this computer.' + #13#10#13#10 +
           'Supervertaler for memoQ installs into memoQ''s own Addins folder, so memoQ has to be ' +
           'installed first. It works with memoQ 11 and 12; older versions have not been tested. ' +
           'If memoQ is installed somewhere unusual, install it in the normal place or get in touch.',
           mbCriticalError, MB_OK);
    Exit;
  end;

  if MemoQIsRunning() then
  begin
    MsgBox('memoQ is running.' + #13#10#13#10 +
           'Close memoQ and run this installer again. memoQ keeps the add-in open while it runs, ' +
           'so the files cannot be replaced underneath it.', mbCriticalError, MB_OK);
    Exit;
  end;

  Result := True;
end;

{ The uninstaller runs in its own process with its own [Code] section, so this
  is a second copy of the check rather than a call to the one above. }
function UninstallMemoQIsRunning(): Boolean;
var
  Res: Integer;
begin
  Result := False;
  if Exec(ExpandConstant('{cmd}'), '/C tasklist /FI "IMAGENAME eq memoQ.exe" | find /I "memoQ.exe"',
          '', SW_HIDE, ewWaitUntilTerminated, Res) then
    Result := (Res = 0);
end;

function InitializeUninstall(): Boolean;
begin
  Result := True;
  if UninstallMemoQIsRunning() then
  begin
    MsgBox('memoQ is running.' + #13#10#13#10 +
           'Close memoQ and run this again. While memoQ is open it holds the add-in files, so they ' +
           'cannot all be removed - which would leave memoQ still loading a plugin you believe you ' +
           'have uninstalled.', mbCriticalError, MB_OK);
    Result := False;
  end;
end;

{ The live document link needs memoQ's own PDF Preview tool, because that is
  where the interface it talks to lives - we deliberately ship none of memoQ's
  code. Said at the end rather than blocking the install: everything else works
  without it, and a customer who does not use that feature should not be stopped. }
procedure CurStepChanged(CurStep: TSetupStep);
var
  Base: String;
  Found: Boolean;
  Rec: TFindRec;
begin
  if CurStep <> ssPostInstall then Exit;

  Found := False;
  Base := ExpandConstant('{commonpf}') + '\memoQ';

  if FindFirst(Base + '\*Preview*', Rec) then
  begin
    try
      repeat
        if FileExists(Base + '\' + Rec.Name + '\MemoQ.PreviewInterfaces.dll') then Found := True;
      until Found or (not FindNext(Rec));
    finally
      FindClose(Rec);
    end;
  end;

  if not Found then
    MsgBox('Installed.' + #13#10#13#10 +
           'One optional extra: the live document link, which lets the AI see the document you have ' +
           'open, needs memoQ''s own PDF Preview tool. It is a free download from memoQ and is not ' +
           'installed on this computer.' + #13#10#13#10 +
           'Everything else works without it.', mbInformation, MB_OK);
end;
